name: D:\projects\cloud_filling\cloud_filler\conda-env
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bokeh=1.4.0=py37_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - click=7.0=py37_0
  - cloudpickle=1.2.2=py_0
  - cytoolz=0.10.1=py37he774522_0
  - dask=2.10.1=py_0
  - dask-core=2.10.1=py_0
  - distributed=2.10.0=py_0
  - freetype=2.9.1=ha9979f8_1
  - fsspec=0.6.2=py_0
  - heapdict=1.0.1=py_0
  - icc_rt=2019.0.0=h0cc432a_1
  - intel-openmp=2019.4=245
  - jinja2=2.10.3=py_0
  - jpeg=9b=hb83a4c4_2
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.1.0=h56a325e_0
  - llvmlite=0.31.0=py37ha925a31_0
  - locket=0.2.0=py37_1
  - markupsafe=1.1.1=py37he774522_0
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - msgpack-python=0.6.1=py37h74a9793_1
  - numba=0.48.0=py37h47e9c7a_0
  - numpy=1.18.1=py37h93ca92e_0
  - numpy-base=1.18.1=py37hc3f5095_1
  - olefile=0.46=py37_0
  - openssl=1.1.1d=he774522_3
  - packaging=20.1=py_0
  - pandas=1.0.0=py37h47e9c7a_0
  - partd=1.1.0=py_0
  - pillow=7.0.0=py37hcc1f983_0
  - pip=20.0.2=py37_1
  - psutil=5.6.7=py37he774522_0
  - pyparsing=2.4.6=py_0
  - python=3.7.6=h60c2a47_2
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyyaml=5.2=py37he774522_0
  - setuptools=45.1.0=py37_0
  - six=1.14.0=py37_0
  - sortedcontainers=2.1.0=py37_0
  - sqlite=3.30.1=he774522_0
  - tbb=2019.4=h74a9793_0
  - tblib=1.6.0=py_0
  - tk=8.6.8=hfa6e2cd_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wheel=0.34.1=py37_0
  - wincertstore=0.2=py37_0
  - xz=5.2.4=h2fa13f4_4
  - yaml=0.1.7=hc54c509_2
  - zict=1.0.0=py_0
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
prefix: D:\projects\cloud_filling\cloud_filler\conda-env
